#!/bin/zsh

export PCURL_URL="http://tests.wordpress.test/wp-json/goba/v1"
# pretty print json from gb plugin endpoints.
function pcurl(){
    local endpoint=$1
    local url="$PCURL_URL/$endpoint"
    local end=" | python -m json.tool"

    echo $url
    if [[ -n $2 ]]; then
        if [[ "$2" == "-t" ]]; then
            end='-w "@${ZSHFILES}pcurl_format.txt"'
        else
            echo "Unknown option $2"
        fi
    fi


    local cmd="curl $url $end"
    echo "$cmd"
    # eval "curl -w \"@${ZSHFILES}pcurl_format.txt\" $url | python -m json.tool"
    eval $cmd
}



export GOBA_VVV_PLUGIN_DIR='/Users/butchwesley/vvv-local/www/wordpress-one/public_html/wp-content/plugins'
export GOBA_VVV_THEME_DIR='/Users/butchwesley/vvv-local/www/wordpress-one/public_html/wp-content/themes'

export GOBA_VVV_TWO_PLUGIN_DIR='/Users/butchwesley/vvv-local/www/wordpress-two/public_html/wp-content/plugins'
export GOBA_VVV_TWO_THEME_DIR='/Users/butchwesley/vvv-local/www/wordpress-two/public_html/wp-content/themes'

export GOBA_VVV_TESTS_PLUGIN_DIR='/Users/butchwesley/vvv-local/www/wordpress-tests/public_html/wp-content/plugins'
export GOBA_VVV_TESTS_THEME_DIR='/Users/butchwesley/vvv-local/www/wordpress-tests/public_html/wp-content/themes'

export GOBA_GH_PLUGIN_DIR='/Users/butchwesley/development/gobananas-plugin/wordpress/plugins'
export GOBA_GH_THEME_DIR='/Users/butchwesley/development/gobananas-plugin/wordpress/themes'

export GOBA_GH_SQL_DIR='/Users/butchwesley/development/gobananas-plugin/sql'
export GOBA_VVV_SQL_DIR='/Users/butchwesley/vvv-local/www/goba_sql'

function goba_vvv_to_github(){
    echo "NOT IMPLEMENTED"
}

function goba_github_to_vvv(){
    rsync -avHE --exclude "*vendor*" $GOBA_GH_PLUGIN_DIR/* $GOBA_VVV_PLUGIN_DIR
    rsync -avHE $GOBA_GH_THEME_DIR/* $GOBA_VVV_THEME_DIR
}

function goba_github_to_vvv_two(){
    rsync -avHE --exclude "*vendor*" $GOBA_GH_PLUGIN_DIR/* $GOBA_VVV_TWO_PLUGIN_DIR
    rsync -avHE $GOBA_GH_THEME_DIR/* $GOBA_VVV_TWO_THEME_DIR
}

function goba_github_to_vvv_tests(){
    rsync -avHE --exclude "*vendor*" $GOBA_GH_PLUGIN_DIR/* $GOBA_VVV_TESTS_PLUGIN_DIR
    rsync -avHE $GOBA_GH_THEME_DIR/* $GOBA_VVV_TESTS_THEME_DIR
}

function goba_vvv_two_to_github(){
    local choice
    $choice=`confirm "Are really sure you want to do this?"`
    echo "${choice}"
}

function goba_send_sql(){
    rsync -avHE $GOBA_GH_SQL_DIR/* $GOBA_VVV_SQL_DIR
}

alias ssh_goba='ssh gobanan4@50.87.187.201 -vi ~/.ssh/butch_id_rsa'