#!/bin/zsh
export GODOT='/Applications/Godot_3_0.app/Contents/MacOS/Godot'

alias godot='eval $GODOT'
alias godot31='/Applications/Godot_3_1.app/Contents/MacOS/Godot'
alias ngodot='open -n $GODOT'
alias godot_loc="find . -name '*.gd' | xargs wc -l"

# $1 = the name of the script
# $2 = pattern for functions (optional)
function list_functions(){
	local cmd="find ./ -name $1 -exec cat {} \; |  grep -n 'func '"

	if [[ "$2" ]]; then
		cmd="$cmd | grep $2"
	fi
	eval $cmd
}

function godot_accessor() {
	name=${1#"_"}
	tab=$'\t'

	read -r -d '' OUTPUT  <<EOM
func get_$name():
${tab}return $1

func set_$name($name):
${tab}$1 = $name
EOM
  echo "$OUTPUT"
	echo "$OUTPUT" | pbcopy
}


function gut(){
  local script=''
  if [[ $1 ]]; then
    script=" -gselect=$1 "
  else
    script=""
  fi

  local t=''
  if [[ $2 ]]; then
    test=" -gunit_test_name=$2"
  else
    test=""
  fi

	local rest_of_args="$3 ${@:3}"
  local options="--debug-collisions --path $PWD -d -s addons/gut/gut_cmdln.gd $script $test $rest_of_args"

	eval "$GODOT $options"
}

# ------------------------
# a bunch of old aliases that I'm not ready to get rid of yet.
# ------------------------
# export GAME='/Users/butchwesley/development/godot/comedyTheGame/godotcomedygame/game'
# export GAME_UNIT_TESTS='poopGame/unit_tests/unit_tests.scn'
#alias godot='open -n /Applications/Godot.app --args '
#alias gut="godot -path $PWD -d -s test/gut/gut_cmdln.gd -gdir=res://test/unit -gexit -gignore_pause"
#alias comgut="godot -path $PWD -d -s res://bitwes_tools/scripts/gut_cmdln.gd -gutloc=res://bitwes_tools/scripts/gut.gd -gdir=res://poopGame/test/unit,res://poopGame/test/integration -gignore_pause -gexit"
#alias play_game='godot -path /Users/butchwesley/development/godot/comedyTheGame/godotcomedygame/game'
#alias godot='/Applications/Godot.app/Contents/MacOS/Godot'
#alias gut_readme_samples='godot -path $PWD -d -s addons/Gut/gut_cmdln.gd -gignore_pause -gdir=res://test/samples/ -gexit -gselect=test_readme_examples.gd'
#export GODOT_USER='~/.godot/app_userdata'
